services:
  notifypublish.api:
    image: ${DOCKER_REGISTRY-}notifypublishapi
    build:
      context: .
      dockerfile: projects/Poc.NotifyPublish/Poc.NotifyPublish.API/Dockerfile
    ports:
      - '5231:8080'
      - '5232:5235'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  notifyOrchestrator.worker:
    image: ${DOCKER_REGISTRY-}notifyorchestrator
    build:
      context: .
      dockerfile: projects/Poc.NotifyOrchestrator/Poc.NotifyOrchestrator.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DB_NOTIFY;User Id=sa;Password=123@Passw0rd;Encrypt=False;
    depends_on:
      - rabbitmq
      - redis
      - sql-server
    networks:
      - mynetwork

  notifySendEmail.worker:
    image: ${DOCKER_REGISTRY-}notifysendemail
    build:
      context: .
      dockerfile: projects/Poc.NotifySend/Poc.NotifySendEmail.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  notifySendSms.worker:
    image: ${DOCKER_REGISTRY-}notifysendsms
    build:
      context: .
      dockerfile: projects/Poc.NotifySend/Poc.NotifySendSms.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  rabbitmq:
    container_name: "rabbitmqcontainer"
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork

  redis:
    container_name: "rediscontainer"
    image: redis
    ports:
      - '6379:6379'
    networks:
      - mynetwork

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=123@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - mynetwork
  
volumes:
  rabbitmq_data:

networks:
  mynetwork:
    driver: bridge